import type { StylesatlifeConfig } from './types';

export const config: StylesatlifeConfig = {
  basePath: '/preview/stylesatlife',
  id: 'stylesatlife',
  name: 'Cleanfirm Stylesatlife',
  tagline: 'Professioneel Schoonmaakbedrijf voor Limburg & Brabant',
  description: 'Cleanfirm Stylesatlife is uw betrouwbare partner voor professionele schoonmaak in de regio Limburg en Brabant. Gevestigd in Geleen leveren wij topkwaliteit aan particulieren en bedrijven.',

  colors: {
    primary: '#2D6A2D',
    primaryHover: '#1A4A1A',
    primaryLight: '#E8F5E9',
    secondary: '#6BAE6B',
    text: '#1A2B1A',
    background: '#FFFFFF',
  },

  contact: {
    address: 'Geleen',
    city: 'Geleen, Limburg',
    phone: '+31 46 000 00 00',
    email: 'info@cleanfirm.nl',
    hours: {
      weekday: '08:00 – 18:00',
      saturday: '09:00 – 15:00',
      sunday: 'Gesloten',
    },
  },

  navigation: [
    { label: 'Over Ons', path: '/over-ons' },
    { label: 'Diensten', path: '/diensten' },
    { label: 'Resultaten', path: '/resultaten' },
    { label: 'Schoonmaaktips', path: '/tips' },
  ],

  hero: {
    title: 'Welkom bij',
    highlight: 'Cleanfirm Stylesatlife',
    subtitle: 'Professionele schoonmaak voor particulieren en bedrijven in Limburg en Brabant. Wij zorgen voor een vlekkeloze omgeving — elke keer weer.',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1920&h=1080&fit=crop',
    cta: 'Bekijk Onze Diensten',
    ctaLink: '/diensten',
    ctaSecondary: 'Maak een Afspraak',
    ctaSecondaryLink: '/contact',
  },

  features: [
    {
      icon: '✅',
      title: 'Gecertificeerd & Ervaren',
      description: 'Ons team werkt volgens professionele normen met gecertificeerde methoden en milieuvriendelijke middelen.',
    },
    {
      icon: '🌿',
      title: 'Milieuvriendelijk',
      description: 'Wij gebruiken uitsluitend biologisch afbreekbare schoonmaakproducten, veilig voor mens en milieu.',
    },
    {
      icon: '🔒',
      title: 'Betrouwbaar & Discreet',
      description: 'Onze medewerkers zijn gescreend en werken discreet. Uw privacy en bezittingen zijn bij ons in veilige handen.',
    },
    {
      icon: '📅',
      title: 'Flexibel & Op Maat',
      description: 'U bepaalt wanneer en hoe vaak. Wij passen ons volledig aan uw wensen en planning aan.',
    },
  ],

  services: [
    {
      id: 'reguliere-schoonmaak',
      name: 'Reguliere Schoonmaak',
      description: 'Wekelijkse of tweewekelijkse schoonmaak van uw woning of kantoor. Stofzuigen, dweilen, sanitair reinigen en alle oppervlakken stofvrij maken.',
      priceLabel: 'Op maat',
      icon: '🏠',
      features: [
        'Vloeren stofzuigen en dweilen',
        'Sanitair grondig reinigen',
        'Keuken schoonmaken',
        'Stof afnemen',
        'Vuilniszakken vervangen',
        'Vast rooster naar wens',
      ],
    },
    {
      id: 'grote-beurt',
      name: 'Eenmalige Grote Beurt',
      description: 'Een grondige eenmalige schoonmaak van uw gehele woning of pand. Inclusief moeilijk bereikbare plekken, kasten, apparaten en binnenzijde ramen.',
      priceLabel: 'Op maat',
      icon: '✨',
      features: [
        'Complete grondige schoonmaak',
        'Binnenzijde kasten en laden',
        'Witte goederen van binnen',
        'Binnenzijde ramen en kozijnen',
        'Badkamer dieptereiniging',
        'Keukens inclusief afzuigkap',
      ],
    },
    {
      id: 'bedrijfsschoonmaak',
      name: 'Kantoor & Bedrijfsschoonmaak',
      description: 'Professionele dagelijkse of periodieke schoonmaak van uw kantoor, winkel of bedrijfspand. Wij zorgen voor een frisse en hygiënische werkomgeving.',
      priceLabel: 'Op maat',
      icon: '🏢',
      features: [
        'Dagelijks of periodiek onderhoud',
        'Sanitaire ruimten reinigen',
        'Pantry en keuken schoonmaken',
        'Ramen en deuren',
        'Ontvangstruimtes verzorgen',
        'Buiten openingstijden indien gewenst',
      ],
    },
    {
      id: 'eindschoonmaak',
      name: 'Eindschoonmaak bij Verhuizing',
      description: 'Woning perfect achterlaten bij vertrek of klaar maken voor de nieuwe bewoner. Wij zorgen dat alles spik en span is voor de oplevering.',
      priceLabel: 'Op maat',
      icon: '🔑',
      features: [
        'Volledige opleverschoonmaak',
        'Alle kamers grondig gereinigd',
        'Keukenapparatuur van binnen',
        'Sanitair dieptereiniging',
        'Ramen binnen en buiten',
        'Geschikt voor inspectie',
      ],
    },
    {
      id: 'bouwschoonmaak',
      name: 'Bouw- & Verbouwschoonmaak',
      description: 'Na een verbouwing of nieuwbouw zorgen wij dat al het bouwstof, puin en vuil grondig verwijderd wordt. Wij leveren uw pand stofvrij en gebruiksklaar op.',
      priceLabel: 'Op maat',
      icon: '🏗️',
      features: [
        'Verwijdering bouwstof en vuil',
        'Reiniging van alle oppervlakken',
        'Vloeren schuren en poetsen',
        'Ramen ontkalken',
        'Sloopafval opruimen',
        'Gebruiksklare oplevering',
      ],
    },
    {
      id: 'glazenwassen',
      name: 'Glazenwassen',
      description: 'Kristalheldere ramen van binnen én buiten. Wij wassen uw ramen en kozijnen professioneel, ook op hoogte. Voor thuis én zakelijk.',
      priceLabel: 'Op maat',
      icon: '🪟',
      features: [
        'Ramen binnen en buiten',
        'Kozijnen en dorpels meenemen',
        'Ook op hoogte (ladders/hef)',
        'Dakramen en serre',
        'Vlekvrij resultaat',
        'Periodiek mogelijk',
      ],
    },
  ],

  about: {
    title: 'Over Cleanfirm Stylesatlife',
    story: 'Cleanfirm Stylesatlife is een professioneel schoonmaakbedrijf gevestigd in Geleen, hart van Limburg. Wij bedienen particulieren, ondernemers en instellingen door de gehele regio Limburg en Brabant. Met een gedreven team van ervaren schoonmaakprofessionals leveren wij dag in dag uit vlekkeloos werk.',
    mission: 'Onze missie is eenvoudig: u een schone, gezonde en prettige leef- en werkomgeving bieden. Wij werken met milieuvriendelijke middelen, houden ons aan strikte kwaliteitsstandaarden en zorgen altijd voor een persoonlijke benadering. Een tevreden klant is ons grootste compliment.',
    image: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=1200&h=800&fit=crop',
    values: [
      'Kwaliteit zonder compromis',
      'Milieubewust & verantwoord',
      'Betrouwbaar en punctueel',
      'Persoonlijke service op maat',
      'Transparante communicatie',
      'Regio Limburg & Brabant',
    ],
  },

  testimonials: [
    {
      id: 1,
      name: 'Yvonne van den Berg',
      role: 'Particuliere klant, Sittard',
      rating: 5,
      text: 'Al meer dan twee jaar laat ik mijn huis wekelijks schoonmaken door Cleanfirm. Het team is altijd vriendelijk, stipt op tijd en het resultaat is elke keer weer perfect. Ik zou ze iedereen aanraden!',
    },
    {
      id: 2,
      name: 'Mark Janssen',
      role: 'Particuliere klant, Geleen',
      rating: 5,
      text: 'Na onze verbouwing stond het hele pand vol stof. Cleanfirm heeft alles in één dag grondig schoongemaakt. Ongelooflijk hoe netjes het resultaat was. Echt een aanrader.',
    },
    {
      id: 3,
      name: 'Sandra Peeters',
      role: 'Kantoormanager, Roermond',
      rating: 5,
      text: 'Wij werken al jaren samen met Cleanfirm voor onze kantoorschoonmaak. Professioneel, discreet en altijd op tijd. Onze medewerkers zijn erg blij met de schone werkomgeving.',
    },
  ],

  gallery: [
    {
      id: 1,
      image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop',
      title: 'Keuken Grondige Reiniging',
      category: 'woning',
    },
    {
      id: 2,
      image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&h=600&fit=crop',
      title: 'Badkamer Dieptereiniging',
      category: 'woning',
    },
    {
      id: 3,
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
      title: 'Kantoor Dagelijkse Schoonmaak',
      category: 'kantoor',
    },
    {
      id: 4,
      image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop',
      title: 'Moderne Kantoorruimte',
      category: 'kantoor',
    },
    {
      id: 5,
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
      title: 'Woonkamer Eindschoonmaak',
      category: 'woning',
    },
    {
      id: 6,
      image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&h=600&fit=crop',
      title: 'Na Verbouwing Oplevering',
      category: 'verbouwing',
    },
    {
      id: 7,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
      title: 'Glazenwassen Woning',
      category: 'woning',
    },
    {
      id: 8,
      image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&h=600&fit=crop',
      title: 'Slaapkamer Schoonmaak',
      category: 'woning',
    },
    {
      id: 9,
      image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop',
      title: 'Nieuwbouw Bouwschoonmaak',
      category: 'verbouwing',
    },
  ],

  tips: [
    {
      id: 'karakteristieke-werkzaamheden',
      title: 'Karakteristieke Werkzaamheden bij Professioneel Schoonmaken',
      excerpt: 'Wat maakt professionele schoonmaak anders dan gewoon even snel opruimen? Ontdek de werkzaamheden die écht het verschil maken.',
      icon: '🧹',
      readTime: '4 min',
      content: [
        'Professioneel schoonmaken is meer dan een snelle ronde met de stofzuiger. Het draait om systematisch werken, de juiste middelen en oog voor detail.',
        'Een van de meest karakteristieke werkzaamheden is het werken van "hoog naar laag". Door te beginnen met hoge oppervlakken zoals schappen, plafondlijsten en bovenkanten van kasten, valt het stof naar beneden en kan het daarna in één keer van de vloer worden verwijderd.',
        'Dieptereiniging van sanitair is een andere sleutelwerkzaamheid. Kalkaanslag, schimmel en vlekken worden met professionele middelen en technieken effectief verwijderd zonder de materialen te beschadigen.',
        'Ontvetten van keukenoppervlakken — inclusief de afzuigkap, fornuisringen en de buitenkant van apparaten — is iets wat in een huishoudelijke schoonmaak vaak wordt overgeslagen maar enorm bijdraagt aan hygiëne en uitstraling.',
        'Het reinigen van moeilijk bereikbare plekken zoals achter radiatoren, onder meubels en in hoeken vraagt om de juiste tools. Professionele schoonmakers beschikken over speciale hulpmiddelen om ook die plekken te bereiken.',
        'Tot slot is het consequent opvolgen van een schoonmaakschema essentieel. Door structureel en regelmatig dezelfde werkzaamheden uit te voeren, blijft uw woning of kantoor continu in topconditie.',
      ],
    },
    {
      id: 'schoonmaak-tips',
      title: '10 Handige Schoonmaaktips voor een Stralend Schoon Huis',
      excerpt: 'Met deze praktische tips houdt u uw woning moeiteloos schoon — en bespaart u tijd en geld.',
      icon: '💡',
      readTime: '5 min',
      content: [
        'Een schoon huis begint bij goede gewoontes. Met de juiste aanpak hoeft schoonmaken niet veel tijd te kosten. Hier zijn onze beste tips:',
        'Werk altijd van boven naar beneden. Begin met plafondhoeken en werk naar de vloer toe. Zo veegt u het stof maar één keer op.',
        'Laat schoonmaakmiddelen even inwerken. Spuit het toilet of de douche in, doe dan eerst iets anders en kom later terug. Het middel doet het werk voor u.',
        'Gebruik microvezeldoeken voor bijna alles. Ze zijn effectiever dan gewone doeken en u heeft minder of helemaal geen schoonmaakmiddel nodig.',
        'Maak kleine rommel dagelijks op. Tien minuten per dag bijhouden scheelt uren in het weekend.',
        'Reinig ventilatieroosters en de afzuigkap met een tandenborsteltje — dat bereikt elke kleine opening.',
        'Maak de vaatwasser en wasmachine maandelijks schoon met een speciale reiniger. Zo gaan ze langer mee en ruiken ze frisser.',
        'Gebruik een pluizenroller over stoelbekleding om haren en pluisjes snel te verwijderen.',
        'Onderhoud uw vloeren met het juiste product. Parket, tegels en laminaat vragen elk een andere aanpak.',
        'Schakel een professional in voor de grote beurt. Een professionele schoonmaak twee à vier keer per jaar houdt uw woning structureel in goede staat.',
      ],
    },
    {
      id: 'vieze-geuren-verwijderen',
      title: 'Vieze Geuren Verwijderen: Zo Doet U Dat Effectief',
      excerpt: 'Ongewenste geuren in huis kunnen hardnekkig zijn. Ontdek welke methoden écht werken en hoe u geuren blijvend aanpakt.',
      icon: '🌸',
      readTime: '4 min',
      content: [
        'Vieze geuren in huis zijn vervelend en soms moeilijk te lokaliseren. De eerste stap is altijd de bron aanpakken — een geurverfrisser maskeert de geur slechts tijdelijk.',
        'Zuiveringszout (baking soda) is een van de meest effectieve en goedkope middelen tegen geuren. Strooi het op tapijt of bekleding, laat het een paar uur intrekken en stofzuig het daarna weg.',
        'Azijn is een krachtig middel tegen schimmel- en muffe geuren. Een schaaltje witte azijn in een ruimte absorbeert geuren overnacht. Verdund met water kunt u het ook gebruiken om oppervlakken mee te reinigen.',
        'Koelkastonaangenaamheden verhelpt u door de koelkast grondig te reinigen en daarna een half bakje zuiveringszout erin te plaatsen.',
        'Rookgeur is een van de hardnekkigste. Was alle textiel, laat de ruimte uitgebreid ventileren en gebruik een luchtzuiveraar voor ernstige gevallen. Wanden en plafond kunnen ook de geur vasthouden en moeten worden gereinigd.',
        'Dierengeuren uit tapijt verwijdert u door eerst de natte plek te deppen (nooit wrijven), daarna zuiveringszout te strooien en na het drogen enzymatische reiniger te gebruiken. Dit breekt de organische stoffen daadwerkelijk af.',
        'Tot slot: regelmatige ventilatie is de beste preventie. Open dagelijks ramen en deuren om verse lucht door de woning te laten stromen.',
      ],
    },
    {
      id: 'vergeten-plekken',
      title: 'Deze Plekken Worden Vaak Vergeten bij het Schoonmaken',
      excerpt: 'Denkt u dat uw huis schoon is? Deze veelgemaakte overloopplekken verzamelen meer vuil dan u denkt.',
      icon: '🔍',
      readTime: '3 min',
      content: [
        'Zelfs de meest ijverige schoonmakers slaan regelmatig dezelfde plekken over. Hier zijn de meest vergeten schoonmaakplekken in huis:',
        'Lichtknopjes en stopcontacten. Dagelijks aangeraakt, zelden gereinigd. Een licht vochtig doekje doet wonderen.',
        'De bovenkant van deuren en kasten. Stof verzamelt zich hier ongestoord. Maak het eens per maand schoon met een uitschuifbaar stofdoekje.',
        'De onderkant van het toilet. De buitenkant, de bodem en de scharnieren van het toilet zijn plekken die bacteriën ophopen maar zelden worden gereinigd.',
        'Afvoerputjes van douche en bad. Het haarfilter en de afvoer zelf verdienen maandelijkse aandacht. Ontvet en desinfecteer voor een hygiënische badkamer.',
        'De wasmachine zelf. De rubberen afdichting rondom de deur van een frontlader trekt schimmel aan. Reinig dit wekelijks met een vochtige doek en laat de deur na elke was op een kier staan.',
        'Gordijnen en vitrages. Deze vangen stof, pollen en geuren. Was ze twee à vier keer per jaar of stofzuig ze voorzichtig.',
        'Tv-afstandsbediening en toetsenbord. De meest aangeraakte voorwerpen in huis — reinig ze met een desinfecterende doekje eens per week.',
      ],
    },
    {
      id: 'matras-schoonmaken',
      title: 'Regelmatig je Matras Schoonmaken is Geen Overbodige Luxe',
      excerpt: 'U slaapt er elke nacht in — maar wanneer heeft u uw matras voor het laatst schoongemaakt? Dit is waarom én hoe u het doet.',
      icon: '🛏️',
      readTime: '4 min',
      content: [
        'Een gemiddeld persoon zweet \'s nachts 0,5 tot 1 liter en verliest huidschilfers. Al dit organisch materiaal trekt huisstofmijt aan en kan leiden tot allergieën en slechte slaapkwaliteit.',
        'Draai uw matras om de drie maanden. Hierdoor slijt het gelijkmatig en blijft het langer ondersteunend.',
        'Stofzuig uw matras maandelijks met de tapijtstofzuiger. Besteed extra aandacht aan de naden en randen waar zich het meeste stof en vuil ophoopt.',
        'Vlekken verwijderen: behandel verse vlekken meteen. Dep (niet wrijven!) met een mengsel van koud water en mild zeep. Gebruik nooit te veel vocht, want een nat matras droogt slecht en bevordert schimmelgroei.',
        'Vlekken van urine verwijdert u het beste met een enzymatische reiniger. Strooi daarna zuiveringszout op de natte plek, laat het drogen en stofzuig het weg.',
        'Laat uw matras regelmatig luchten. Haal het beddengoed eraf en open de ramen. Een paar uur frisse lucht doet wonderen voor de hygiëne.',
        'Investeer in een waterdichte matrasbeschermer. Dit houdt het matras schoon, verlengt de levensduur en maakt reiniging eenvoudiger.',
        'Een professionele matrasreiniging is aan te raden eens per jaar — zeker voor mensen met allergie of kleine kinderen.',
      ],
    },
  ],
};
