export const config = {
  basePath: '/preview/taxi-nelissen',
  id: 'taxi-nelissen',
  name: 'Taxi Nelissen',
  tagline: 'Uw betrouwbare taxipartner in de regio Maastricht – sinds 1962',
  description: 'Taxi Nelissen verzorgt al meer dan 60 jaar comfortabel en betrouwbaar vervoer in de regio Maastricht.',
  colors: {
    primary: '#E05A1C',
    primaryHover: '#C44E18',
    primaryLight: '#FDF0EA',
    navy: '#162140',
    navyLight: '#1E2F55',
    text: '#1A1A2E',
    muted: '#6B7280',
    background: '#FAFAF8',
  },
  contact: {
    address: 'Maastricht, Zuid-Limburg',
    phone: '043 123 45 67',
    phoneHref: '+31431234567',
    email: 'info@taxinelissen.nl',
    hours: { weekday: '24 uur per dag', weekend: '24 uur per dag' },
  },
  navigation: [
    { label: 'Home', path: '/' },
    { label: 'Particulier vervoer', path: '/particulier-vervoer' },
    { label: 'Zakelijk vervoer', path: '/zakelijk-vervoer' },
    { label: 'WMO Maastricht', path: '/wmo-maastricht' },
    { label: 'Ziekenvervoer', path: '/ziekenvervoer' },
    { label: 'Vacatures', path: '/vacatures' },
    { label: 'Contact', path: '/contact' },
  ],
  services: [
    { id: 'particulier', name: 'Particulier Vervoer', icon: '🚖', description: 'Comfortabel en betaalbaar vervoer voor particulieren in de regio Maastricht. Van dagje uit tot luchthaventrip – wij brengen u veilig op bestemming.', features: ['Vaste all-in prijzen', 'Grote bagage welkom', 'Retourrit mogelijk', 'Vluchten worden gevolgd'] },
    { id: 'zakelijk', name: 'Zakelijk Vervoer', icon: '💼', description: 'Professioneel zakelijk vervoer voor bedrijven in de regio. Stipt, discreet en representatief – uw zakenpartners verdienen het beste.', features: ['Factuur op naam bedrijf', 'Vaste chauffeur mogelijk', 'Directievervoer', 'Contracten voor vaste klanten'] },
    { id: 'wmo', name: 'WMO Maastricht', icon: '🏛️', description: 'Als erkend WMO-vervoerder in Maastricht verzorgen wij zorgvuldig vervoer voor mensen met een beperking of ziekte.', features: ['Erkend WMO-vervoerder', 'Hulp bij in- en uitstappen', 'Aangepaste voertuigen', 'Geduldig en zorgzaam'] },
    { id: 'ziekenvervoer', name: 'Ziekenvervoer', icon: '🏥', description: 'Betrouwbaar ziekenvervoer naar MUMC+ en andere ziekenhuizen in de regio. Wij rijden u heen en wachten indien gewenst op u.', features: ['Ziekenhuis Maastricht (MUMC+)', 'Retourrit inbegrepen', 'Geduldig & zorgzaam', 'Op tijd gegarandeerd'] },
    { id: 'airport', name: 'Luchthavenvervoer', icon: '✈️', description: 'Stressvrij naar het vliegveld met Taxi Nelissen. Wij monitoren uw vlucht en staan klaar bij aankomst.', features: ['Vlucht monitoring', 'Vaste all-in prijs', 'Alle grote luchthavens', 'Vroeg boeken = vaste prijs'] },
    { id: 'groepsvervoer', name: 'Groepsvervoer', icon: '👥', description: 'Voor groepen tot 8 personen hebben wij ruime voertuigen beschikbaar. Perfect voor uitjes, events of bedrijfsreizen.', features: ['Tot 8 personen', 'Bruiloften & events', 'Bedrijfsuitjes', 'Offerte op maat'] },
  ],
  features: [
    { icon: '😊', title: 'Service met een lach', description: 'Onze medewerkers zijn flexibel, maken graag een praatje en staan garant voor een aangename taxirit.' },
    { icon: '€', title: 'Scherpe tarieven', description: 'Naast onze service staan wij voor een zo scherp mogelijke prijs voor onze klanten.' },
    { icon: '🎓', title: 'Ervaring', description: 'Wij zijn al meer dan 60 jaar een betrouwbare speler in de regio Maastricht.' },
    { icon: '🕐', title: '24/7 Bereikbaar', description: 'Dag en nacht voor u beschikbaar. Vroeg vliegtuig of laat avondje? Wij staan klaar.' },
  ],
  airports: [
    { name: 'Maastricht Aachen Airport', time: '±20min' },
    { name: 'Eindhoven Airport', time: '±45min' },
    { name: 'Schiphol Amsterdam', time: '±2u15' },
    { name: 'Brussel Airport', time: '±1u30' },
    { name: 'Düsseldorf Airport', time: '±1u' },
    { name: 'Frankfurt Airport', time: '±2u' },
  ],
  heroImage: 'https://images.unsplash.com/photo-1503470069725-dacc9110076e?q=80&w=1470&auto=format&fit=crop',
  about: {
    title: 'Over Taxi Nelissen',
    story: 'Opgericht in 1962 is Taxi Nelissen uitgegroeid tot een van de meest vertrouwde taxibedrijven in de regio Maastricht. Generaties lang rijden wij voor particulieren, bedrijven en zorginstellingen. Onze chauffeurs kennen de regio als hun broekzak.',
    mission: 'Onze missie is simpel: u veilig, op tijd en met een glimlach van A naar B brengen. Of het nu gaat om een ritje naar de dokter, een zakelijke afspraak of een vliegreis – wij zijn er voor u.',
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1200&h=800&fit=crop',
    values: ['Veiligheid staat altijd voorop', 'Stiptheid als standaard', 'Persoonlijke aandacht voor elke klant', 'Meer dan 60 jaar ervaring en vertrouwen'],
  },
  testimonials: [
    { id: 1, name: 'Marianne Janssen', role: 'Vaste klant, Maastricht', rating: 5, text: 'Al jaren rij ik met Taxi Nelissen naar het ziekenhuis. Altijd op tijd, altijd vriendelijk. Ze weten precies wat ik nodig heb en ik voel me veilig bij hen.' },
    { id: 2, name: 'Robert Hermans', role: 'Zakelijke klant', rating: 5, text: 'Voor onze directieritten vertrouwen wij al jaren op Taxi Nelissen. Professioneel, discreet en altijd stipt. Factuur op naam van het bedrijf, geen gedoe.' },
    { id: 3, name: 'Familie Willems', role: 'Luchthavenvervoer', rating: 5, text: 'Met het hele gezin naar Schiphol – de chauffeur stond precies op tijd voor de deur. Ruim genoeg voor alle koffers en een gezellige chauffeur erbij. Top!' },
  ],
  vacatures: [
    { title: 'Taxichauffeur (parttime/fulltime)', type: 'Parttime / Fulltime', description: 'Ben jij een vriendelijke, betrouwbare chauffeur met kennis van de regio? Wij zoeken collega\'s die graag mensen helpen.', requirements: ['Geldig taxipas (CCV)', 'Rijbewijs B', 'Goede kennis van de regio', 'Klantvriendelijk'] },
    { title: 'Zorgchauffeur WMO', type: 'Parttime', description: 'Voor ons WMO-vervoer zoeken wij een zorgzame chauffeur met hart voor de doelgroep. Geduld en empathie zijn bij jou vanzelfsprekend.', requirements: ['Ervaring met zorgvervoer', 'Taxipas', 'Geduldig en empathisch', 'Flexibele beschikbaarheid'] },
  ],
};
